server:
  port: 8040

spring:
  application:
    name: nacos-discovery-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.100:8848
        metadata:
          name: gateway
    gateway:
      routes:
        - id: nacos-discovery-provider
          uri: lb://nacos-discovery-provider
          #类似nginx的location，请求这个地址的会被转发
          predicates:
            - Path=/provider/**
          #设置跳过第一个context-path（一般是项目名）
          filters:
            - StripPrefix=1
        - id: nacos-discovery-consumer-feign
          uri: lb://nacos-discovery-consumer-feign
          predicates:
            - Path=/consumer-feign/**
          filters:
            - StripPrefix=1